
Estru:={ ;
         { 'ID'           ,  'N',   10,    0 } , ;
         { 'IDREGIS'      ,  'N',   10,    0 } , ;
         { 'TRANSAC'      ,  'N',   10,    0 } , ;
         { 'COS'          ,  'N',    4,    0 } , ;
         { 'FFAC'         ,  'D',    8,    0 } , ;
         { 'NPRES'        ,  'N',    2,    0 } , ;
         { 'CSOC'         ,  'N',    4,    0 } , ;
         { 'TIPO'         ,  'N',    1,    0 } , ;
         { 'NLOTE'        ,  'N',   10,    0 } , ;
         { 'NITEM'        ,  'N',    2,    0 } , ;
         { 'CPRAC'        ,  'N',    8,    0 } , ;
         { 'PRACTICAS'    ,  'C',   42,    0 } , ;
         { 'FPRAC'        ,  'D',    8,    0 } , ;
         { 'CANT'         ,  'N',    3,    0 } , ;
         { 'COPER'        ,  'C',    3,    0 } , ;
         { 'FACTU'        ,  'D',    8,    0 } , ;
         { 'HACTU'        ,  'C',    5,    0 } , ;
         { 'COPERMOD'     ,  'C',    3,    0 } , ;
         { 'FMOD'         ,  'D',    8,    0 } , ;
         { 'HMOD'         ,  'C',    5,    0 } , ;
         { 'FDEL'         ,  'D',    8,    0 } , ;
         { 'HDEL'         ,  'C',    5,    0 } , ;
         { 'COPERDEL'     ,  'C',    3,    0 } , ;
         { 'OBSE'         ,  'M',   10,    0 } , ;
         { 'CMOTIVO'      ,  'N',    3,    0 } , ;
         { 'PACIENTE'     ,  'C',   30,    0 } ;
        }
